<a href="https://colab.research.google.com/github/vineetsing-h/NumPy/blob/main/Phase_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

## Creating array from list


In [7]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ",arr_1d)


arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array: ",arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


## List vs numpy array


In [9]:
py_list = [1,2,3]
print("Python list multiplication ", py_list*2)

np_array = np.array([1,2,3])   # element wise multiplication
print("Python array multiplication ",np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time()-start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time()-start)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time:  0.11193060874938965

 Numpy operation time:  0.010095596313476562


### Creating array from scratch


In [14]:
zeros = np.zeros((3,4))
print("zeros array: \n",zeros)

ones = np.ones((2,3))
print("ones array: \n",ones)

full = np.full((2,2), 7)
print("full array: \n",full)

random = np.random.random((2,3))
print("random array: \n",random)

sequence = np.arange(0, 11, 2)
print("sequence array: \n",sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.95275418 0.7031805  0.35154112]
 [0.32112125 0.09353594 0.88721333]]
sequence array: 
 [0 2 4 6 8]


## Vector, Matrices and Tensor


In [16]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrice = np.array([[1,2,3],
                    [4,5,6]])
print("Matrice: ", matrice)

tensor = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrice:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array properties


In [17]:
arr = np.array([[1,2,3],[4,5,6]])
print("Shape", arr.shape)  # rows,column
print("Dimension", arr.ndim)
print("Size", arr.size)   # total number of elements
print("DataType", arr.dtype)  # int64

Shape (2, 3)
Dimension 2
Size 6
DataType int64


## Array Reshaping

In [23]:
arr = np.arange(12)
print("Original array: ", arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped array", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ",flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()

# Transpose
transpose = reshaped.T
print("\n Transpose array ",transpose)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
